test:add RejectedProxyInvocationHandlerTest
opengoofy/hippo4j pull request #1199
Opened 2023-04-27 15:08 UTC by z-y-hang

Fixes #ISSUSE_ID

Changes proposed in this pull request:
- 

> Check mailbox configuration when submitting. [Contributor Guide](https://hippo4j.cn/community/contributor-guide)

2023-04-28 08:16 UTC, magestacks commented on hippo4j-core/pom.xml
> +            <artifactId>mockito-inline</artifactId>
Add scope as test

2023-04-28 08:16 UTC, magestacks commented on hippo4j-core/src/test/java/cn/hippo4j/core/proxy/RejectedProxyInvocationHandlerTest.java
> +
Remove extra blank lines.

2023-04-28 08:17 UTC, magestacks commented on hippo4j-core/src/test/java/cn/hippo4j/core/proxy/RejectedProxyInvocationHandlerTest.java
> +
Remove extra blank lines.

2023-04-28 08:44 UTC, iwangjie requested changes

2023-04-28 08:44 UTC, iwangjie commented on hippo4j-core/src/test/java/cn/hippo4j/core/proxy/RejectedProxyInvocationHandlerTest.java
> +        Assertions.assertThrows(Throwable.class, () -> handler.invoke(null, mockMethod, mockArgs));
add rejectCount after value check.

2023-04-29 09:51 UTC, magestacks approved these changes

2023-04-29 09:52 UTC, magestacks approved these changes

2023-04-29 09:57 UTC, iwangjie approved these changes

2023-04-29 09:58 UTC, merged